config/routes.rb
Rails.application.routes.draw do
  resources :wishes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/wish.rb
class Wish < ApplicationRecord
  validates :writer,  presence: true, length: { maximum: 25 }
  validates :context, presence: true, length: { maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  def new
    @wish = Wish.new
  end

  def index
    @wishes = Wish.all
  end

  def show
    @wish = Wish.find(params[:id])
  end

  def create
    @wish = Wish.new(wish_params)
    if @wish.save
      redirect_to wishes_path
    else
      render 'new'
    end
  end

  def destroy
    @wish = Wish.find(params[:id])
    if @wish.destroy
      flash[:notice] = '削除に成功しました'
      redirect_to wishes_path
    else
      flash[:notice]  = '削除に失敗しました'
    end
  end

  def edit
    @wish = Wish.find(params[:id])
  end

  def update
    wish = Wish.find(params[:id])
    if wish.update(wish_params)
      redirect_to wishes_path
    else
      render 'edit'
    end
  end

  private

  def wish_params
    params.require(:wish).permit(:context, :writer)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Negaigoto</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <header>
    <nav class="navbar">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "新規作成", new_wish_path %></li>
        <li class="nav-item"><%= link_to "一覧", wishes_path%></li>
      </ul>
    </nav>
  </header>
  <%= yield %>
</body>

</html>

app/views/wishes/_form.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= form_with model: wish do |f| %>
        <div class="form-group">
          <%= f.label :writer, class: 'form-label' %>
          <%= f.text_field :writer, class: 'form-control', placeholder: '名前を入れてね', required: true %>
        </div>

        <div class="form-group">
          <%= f.label :context, class: 'form-label' %>
          <%= f.text_field :context, class: 'form-control', placeholder: '願い事を入れてね', required: true %>
        </div>

        <div class="float-end mt-5">
          <%= f.submit '願う', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/wishes/edit.html.erb
<%= render 'form', wish: @wish %>

app/views/wishes/index.html.erb
<div class="container mt-5">
  <div class="row">
    <% @wishes.each do |wish| %>
      <div class="col-md-4 mb-4">
        <%= link_to wish_path(wish.id), class: "card text-decoration-none text-dark" do %>
          <div class="card-body">
            <h5 class="card-title"><%= wish.context %></h5>
            <p class="card-text"><small class="text-muted">by: <%= wish.writer %></small></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="container mt-4">
  <%= link_to "新規作成", new_wish_path, class: "btn btn-primary" %>
</div>

app/views/wishes/new.html.erb
<div class="container mt-5">
  <h1 class="mb-4">新しい願いごと</h1>

  <% if @wish.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading"><%= pluralize(@wish.errors.count, "error") %>つのエラーのため保存できませんでした。</h4>
      <ul>
        <% @wish.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form', wish: @wish %>
</div>

app/views/wishes/show.html.erb
<div class="container">
  <div class="sock">
    <h2><%= @wish.context %></h3>
    <h3 class="writer"><%= @wish.writer %></h2>
  </div>
</div>